version: '3'
services:
  web:
    user: "1000:1000"
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    container_name: apache-web
    volumes:
      - ./src:/var/www/html/apache-sample

  db:
    image: mariadb:10.1.48
    container_name: apache-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: